### ISSUE TITLE
[BUG] Global modifier for Griffin School block character sheet

### ISSUE THREAD

**Issue by WitcherFromPoznan** [witchertrpg-foundryvtt/TheWitcherTRPG#145]
I don't know why but if you set the global modifier of the griffin school in the character sheet, this card gets blocked. I checked and this problem doesn't occur with other schools. When you drag from compedium and drop to sheed you cannot eddit wepons, modifiers and so on.

I don't know if this is bug of sheet or compendium.

**Comment by Stexinator** [comment]
You should have an error when you press f12. I need that too :)

**Comment by WitcherFromPoznan** [comment]
> You should have an error when you press f12. I need that too :)

foundry.js:631 Error: An error occurred while rendering WitcherCharacterSheet 40. Cannot read properties of undefined (reading 'tags')
[Detected 1 package: system:TheWitcherTRPG(v12.3.0)]
    at Hooks.onError (foundry.js:630:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:189:56)
    at foundry.js:5770:13Caused by: TypeError: Cannot read properties of undefined (reading 'tags')
[Detected 1 package: system:TheWitcherTRPG(v12.3.0)]
    at witcherActor.js:334:40
    at Array.filter (<anonymous>)
    at WitcherActor.getArmorEcumbrance (witcherActor.js:334:14)
    at WitcherActor.updateDerived (witcherActor.js:91:29)
    at WitcherCharacterSheet.statListener (statMixin.js:224:61)
    at WitcherCharacterSheet.activateListeners (WitcherActorSheet.js:193:14)
    at WitcherCharacterSheet.activateListeners (WitcherCharacterSheet.js:25:15)
    at WitcherCharacterSheet._render (foundry.js:5842:10)
    at async WitcherCharacterSheet._render (foundry.js:6547:5)
    at async WitcherCharacterSheet._render (foundry.js:7133:5)

**Comment by Stexinator** [comment]
The problem is the empty special modifier. You can fix it locally by deleting it

**Comment by WitcherFromPoznan** [comment]
> The problem is the empty special modifier. You can fix it locally by deleting it

Oh it works thank you!

**Comment by Stexinator** [comment]
General fix will be available in next version
